### PR TITLE
- Add BluePay Gateway

### PR DESCRIPTION
**Pull request by rastographics**
I really need to keep our current payment processor, BluePay, so I added another Gateway that implements IGateway similar to the existing ones.

I have tested and successfully processed simple payments with this integration. I have not yet tested managed giving and saved profiles yet, but I will soon.

If you have any questions or concerns please let me know. Otherwise, can this be pulled in?

NOTES:
My biggest concern was where to store the "vault ID", since the other gateways have their vault IDs hard-coded into database (paymentInfo table). 
To keep from breaking anything, I just stored it in TransNational's field for now. This works fine of course, but it could be confusing to other developers, and also cause problems in future for churches who happen to switch from one gateway to another.

Wondering if you are open to any improvements to the way vaultID's are stored so that in the future, new gateways can be easily added without changing DB schema?

### CODE REVIEW

**Comment by jartram** [comment]
Hello David,

We talked a while back ago. 

We are a software development company founded by sons of God as well as your company.

We've been working on a service that definitely could be a good addon to BVCMS.

We developed a common service where you can add multiple payment gateway processors and interface with them using one common API.

There are other 2 companies on market that offer this service, and just one of them could represent a competitor for use.

We currently have 97 companies we offer that service before the to be launched to the public and they all have decide to keep using our service permanently because it saves time and money and their customers loves it.

Our service is called APT Gateway. Once you implement its API in your code you can use any of the top 20 payments gateways in the market. And you can set or swap to the other one without making any single code change. Even your customer can set it up by themselves.

What we looking is to make some partnership or collaboration with you as we are planning to offer cloud storage and processing for BVCMS commercially to the public as part of our lines of products.

In APT Gateway you can create sub accounts (100% isolated) for your customer and they can see their payments, make payments manually, refunds, configure recurring payments ,create email templates and many other options.  

If you would like to know more or try out our product just let me know.

http://aptgateway.com/






____

**Comment by davidcarroll** [comment]
Thank you.  You have caught us at a particularly busy time as we are behind on several significant deadlines that are impacting our business being able to proceed (rebranding initiative and new website etc) and must get caught up. Mo and Brian will be looking at this when they have time. 

Joel, are you a current client of ours?

Regarding the db schema, the only issue is doing some sort of conversion to the new schema for all of our clients existing data. Beyond that, we have no problem updating the schema either and do it all the time, particularly if we have a conversion program already tested and at the ready.

We had not planned on adding any additional gateways beyond the three we have, but if you have done all the work and it passes all of your needs to go live, we will certainly consider accepting the pull request after we have reviewed everything. We are looking forward to taking a look at your code and running it through the paces. It would be most helpful if you would finish your testing first so that we could proceed with confidence that it satisfy our client.

Looking forward to seeing more on this project to implement BluePay's gateway into BVCMS. Again, thank you.

**Comment by rastographics** [comment]
Thanks David.

Yes we are a current client. (nwbbc our account subdomain).
I will make sure everything checks out with managed giving, refunds, batch reports, etc and then I'll report back.

Thanks, really looking forward to being able to use online giving that hooks right up to our contribution statements.

**Comment by davidcarroll** [comment]
Thanks Joel,

I thought I recognized that name. Blessings to you!

**Comment by rastographics** [comment]
I moved this to another branch in my fork and I'll submit a PR from there, so I'm closing this down.

**Pull request closed without merging**
