### PR TITLE
Implement remaining milestones for Redeemer

### PR DESCRIPTION
**Pull request by drmohundro**
This includes the following features:

* Small Group Finder enhancements (mobile responsive, finder-specific layouts, etc.)
* The Resources system (new feature to support posts, attachments, etc.)
* Additional settings to support more granular control by Org Leaders for Redeemer's CG system

(I just rebased `upstream/master` in so this should merge fine right now)

### CODE REVIEW

**Comment by davidcarroll** [comment]
Mo, this looks like a clean pull request. Thanks for keeping it that way. I am going to pull it into a clearfunction branch using git command line. So I can review the code from there. Then, I will merge into master once the review is done. I am not expecting to find any issues but if there are any that I have questions about, I'll comment in Trello.

**Comment by drmohundro** [comment]
Okay, sounds good to me!

**Comment by davidcarroll** [comment]
I have been reviewing all the code this morning. Things are looking good so far. I just got into the changed on the OrgSearch page. See Trello card about that. Proceeding...

**Comment by drmohundro** [comment]
Gotcha - I responded on Trello with some explanation and samples.

**Comment by davidcarroll** [comment]
@karenworrell I am done reviewing the code. I have a few questions for Mo on Trello and he has answered one of them. We can discuss whether we need to test a few more things. I am going to publish this to *.tpsdb.work. It will have all my current master branch code merged into the clear-function branch. If another round of testing does not turn up any problems, I will merge to master and then publish to production.

**Comment by davidcarroll** [comment]
@drmohundro I am going to put trialdb.tpsdb.work back into the wildcard mix *.tpsdb.work. No more commits until I am published to production after we test one final time on .work with my current `master` branch merged into a `clear-function` branch (unpublished)

**Comment by drmohundro** [comment]
@davidcarroll sounds good! Also, got it, no more commits! 👍

**Comment by davidcarroll** [comment]
@drmohundro This pull request has been merged into master and published to production. Good job to you and the Clear Function folks on all this. My code review went very smoothly and everything looked very consistent with our style and approach to coding. This was a massive project and we look forward to getting it all documented and publicised for all of our clients over the next months. And special Thank you to Redeemer Presbyterian Church for sponsoring this project!

**Comment by davidcarroll** [comment]
And seriously, you all have @karenworrell to thank for all the testing and diligence on making sure that none of this breaks any existing functionality for all our clients. This pull request would have been a nightmare without all her work to make us all feel comfortable during this final stage. Thank you @karenworrell!

**Pull request closed without merging**
