### PR TITLE
Email Replacement Codes

### PR DESCRIPTION
**Pull request by hkouns**
I am preparing to send out a mass email to everyone that has contributions this year.  I would like to include their statement options in the email for reference.  And encourage them to go online to manage the options as well as to verify contributions and later print out their statements.

I added replacement codes for:
- Electronic Statements  (electronic only or paper)
     + {estatement}
          - "Online Electronic Statement Only"
          - "Printed Statement in Addition to Online Option"

- Statement Option (Indiv, joint, none)
     + {statementtype}
          - "Individual"
          - "Joint"
          - "None"

- Receive SMS (yes or no)
     + {receivesms}
          - "Yes"
          - "No"

Here is an example from when I was testing different codes:

replacementcodes

### CODE REVIEW

**Comment by davidcarroll** [comment]
Good idea

**Comment by hkouns** [comment]
Please know that this question is not meant in any way to be pressure ... just information gathering.

I was planning to send a Thank You email to our contributors prior to Christmas.  In the Draft I am sending around for staff to review, I currently have a section with these replacement codes.  Do you think these will be incorporated by then or should I send without the codes?

Again, no pressure...

**Comment by davidcarroll** [comment]
Heath, just wanted to make sure you saw that I merged and published this so you could get your email out.

**Comment by hkouns** [comment]
@davidcarroll, 
Thanks! I appreciate it!

**Pull request merged**
