### PR TITLE
ReScope "Room Notices" to "Org Assignment Notices"

### PR DESCRIPTION
**Pull request by hkouns**
Use case: during our VBS we do not assign rooms to each crew... however I still wanted to send a notice of which crew (org) they were in along with the Leader.  I can customize the content of the email to leave out the room number... but the subject still references the "Room Assignment".

The only visible change of this Commit in the GUI is that the "Email Room Notices" button on the Manage Org Member Page now reads "Email Org Assignment Notices"

Also changes text in admin notice emails to read "Org Assignment notices sent to:" instead of "room notices sent to:" 

Also adds the ability to customize the subject of the notice emails with a special content Text File... called:  OrgMembersModel_SendMovedNotices_Subject

The text can contain replacement codes for {name}, {org}, {room}, {leader}, {phone}, {church}
If file does not exist then it defaults to existing subject line:"{0} room assignment".Fmt(i.OrganizationName)

### CODE REVIEW

**Comment by davidcarroll** [comment]
Heath, this is interesting. I like the use case, but we will need to test this to make sure that this does not surprise anybody and that it does not require any changes for it to work like they are used to. This was primarily used to handle promotions which are currently ongoing during the month of August and the emails are sent to notify parents about their children's new room assignments.

**Comment by davidcarroll** [comment]
@drmohundro Please check out a new branch and pull this, then publish to test2 so we can test this with @karenworrell

**Comment by hkouns** [comment]
Thanks @davidcarroll 

@karenworrell if you have any questions, please let me know.  If you like it ... I can go ahead and update the documentation page and write up how to modify the Subject.  (if the file is not present then it defaults to the current subject)

FYI... here is email as we used it for VBS... notice that the subject references a room assignment... but it is not mentioned in the body of the email.

++++++++++++++++++++++++++++++++++++++++++++++++
**From:** Laura Mcdowell [mailto:mclaurab@hotmail.com] 
**Sent:** Saturday, June 27, 2015 6:16 PM
**To:** Leah Kouns; pkouns@hotmail.com
**Subject:** VBS - A13 room assignment

Leah Kouns,
We are so excited that VBS is almost here.  Thank you for pre-registering it makes check-in flow so much smoother.

You have been assigned to the following crew: **VBS - A13** . The leader's name is **Aaron Hartsfield** *.
 
When you get to the church, please go to one of the iPADs in the lobby and enter your phone number to check-in. A label will print for the child to wear along with a security label for the Parent.  Then you can go into the great room and find the sign with your Crew Number.  Your Crew and Leader will be in the row beside the sign. We can’t wait to see you there! 
Please call Laura McDowell (540-230-2244) if you have any questions about registration or Checkin.  Contact Heather Woolwine or the Church office (5403820719) if you have general questions about VBS.

Thank you!

Heather and Laura
Good Shepherd Baptist Church

 -* *Note: For your peace of mind, all Children's Ministry Volunteers (18 and older) at GSBC undergo background check prior to volunteering.*

**Comment by hkouns** [comment]
FYI... this idea was originally submitted via a Support Request:  gsbcfamily [5825]

**Comment by davidcarroll** [comment]
Heath, I have not even discussed this yet with Karen. We are very slammed right now. August is a very busy month with promotion and preparing for the Fall programs. We will just have to address this when things settle down a bit.

**Comment by hkouns** [comment]
@davidcarroll, I understand... I had meant to add the reference to the Support Request earlier and just remembered when I submitted the other Pull request (for {insertdraft:name} replacement code)

**Comment by drmohundro** [comment]
FYI, I manually merged this into [pr54-changes](https://github.com/bvcms/bvcms/tree/pr54-changes) so that it can be tested before we bring it into master.

**Comment by hkouns** [comment]
Thanks Mo...

Can you tell me if you are currently working/planning on any other changes to the Manage Org Member Page?

I am currently working on a modification to make the Small Group filter work more like the one on the Org page.  (load small groups into a selector based on the Source org,  allow  multiple small groups, exclude, etc.)
I have the copied over the form controls from the org page and have it mostly working at this point... just need to finalize the filtering and clean up the page.
  
I was also looking at putting a "clear" button on the page and implementing the Popup help Info icons.

Just wanted to make sure I was working toward a common target....and that I am not duplicating something you or david are working on behind the scenes.

Thoughts??  

(let me know if you want me to move this topic to an "issue" instead of discussing on this pull request.)

**Comment by davidcarroll** [comment]
We are not working on this page

**Comment by davidcarroll** [comment]
Heath, We have this in a separate branch from master now called pr54-changes.  It is published to one of our test servers. Karen is aware of this and will validate it early next week. At that point we will merge that branch into master. You can see some changes I made your code, mainly to not use a dedicated content record just for the subject line. Now, it uses the Title of the existing content for that room notices email to store the subject in.  We have used this pattern in various other places.

**Comment by hkouns** [comment]
Thanks for the feedback... I had considered trying to use the Title... but I didn't know if it would support the replacement codes.  I should have tried to pursue that line of thinking further.

**Comment by davidcarroll** [comment]
Heath, I edited the "email" you included in this thread since it contained phone numbers and names. This is a public site.

**Comment by hkouns** [comment]
Thanks David,  I had previously gotten rid of the email address... I guess I didn't think about the names and addresses since they are on the church website.  But your changes are best... thanks.

**Comment by davidcarroll** [comment]
Karen tested this and we should be good to go now that Bellevue is done with promotion.  Promotion Sunday occurs this weekend. 

I probably won't publish these two pull requests until Sunday night. 

Also, I noticed that these two pull requests got conflated (they both had the org members management code). Not sure how that happened, but in the future, please keep your projects isolated into separate branches if you do more than one pull requests at the same time. These things can get confusing since everything is a moving target.

**Comment by hkouns** [comment]
David,  Yes... I realized the issue when I made the second PR.  The problem was that the first PR I made was from GSBCfamily/master and then I used it as the basis for the next Branch from which the PR was made.  From now on, I will only issue PR from branches off of Master and I will not merge any branches into Master until after the PR has been approved.  Actually I guess I will just continue to update GSBCfamily/master from BVCMS/master to keep it up to date.  Sorry for the confusion.

**Pull request merged**
