### PR TITLE
Mobile App: Roll List filtered for Sub-Group leaders

### PR DESCRIPTION
**Pull request by rastographics**
Continues discussion from [this pull request](https://github.com/bvcms/bvcms/pull/109)
Had to create new pull request due to git issues on my end.

Test server http://dev.nwbbc.org:44401
Username: admin
Password: touchpoint.1

### CODE REVIEW

**Comment by davidcarroll** [comment]
You'll want to give @karenworrell a quick synopsis on what she is to expect, either in text or in a short video or both.

**Comment by davidcarroll** [comment]
One of your previous videos may work

**Comment by rastographics** [comment]
Should I email her or include in this PR?

**Comment by rastographics** [comment]
@karenworrell
This feature allows the Roll List to be filtered by Subgroup in the Mobile App Attendance.
It works by assigning "Leaders" to Sub-Groups. 
Once a user is a Leader of a Sub-Group(s), they will only see the members of that(those) particular Sub-Group for attendance in the app.

Any members of an Org who are not in any sub-group, or who are in a sub-group that has no leaders, will be shown on the Roll List of the Org's Main Leader (Teacher, etc.). 
This is so class members do not "fall through the cracks" and end up not being on any leader's Roll sheet.
Also, guests will show up on the Main Leader's roll list (until made a member and assigned to a sub-group that has it's own leader(s)).

To enable this feature for an Organization:

1. Organization Details > Settings > Attendance > Filter Attendance Roster By Subgroup

Now you can assign Leaders to Sub-Groups. 
1. Sub-Group Management > Sub-Group Members
2. Choose a Target Group you want to assign leaders to.
3. Select the members you would like to assign as leaders.
4. Actions Button > Make Selected a Leader of Target Group
  - If any selected people are not already in the Target Group, they are added to the Target Group as well as made a Leader.

Remove leaders:

1. Sub-Group Management > Sub-Group Members
2. Choose a Target Group you want to remove leaders from.
3. Select the members you would like to remove as leaders.
4. Actions Button > Remove Selected as Leader of Target Group
    - No people are removed from the Target Group…only removed from being the Leader.

[Video Example](https://vimeo.com/163613071/ff6c0a2e83)

**Comment by karenworrell** [comment]
Thank you. I'll set up the scenarios and test. I really appreciate the info and video!

**Comment by davidcarroll** [comment]
Email will be fine. Karen at bvcms.com

**Comment by karenworrell** [comment]
Here are my preliminary findings:

Issue #1: When recording attendance as a Group Leader, if you add a new guest, you do not see that the record is added. That is because you are limited to viewing just your sub-group. User: Another David, OrgLeadersOnly role, Group Leader of David sub-group.

How did you intend for that to work, Joel?

Issue #2: Those NOT in a sub-group are NOT displaying for the Class Leader. User is The Admin, Mbr Type = Leader, the Org Leader Type = Leader, The Admin is Leader of the Admin sub-group. His group displays but not the person that is enrolled and not in a sub-group.

The only way I could get someone NOT in a sub-group to display for attendance on the App, was to log in as a leader in the class who is NOT a sub-group leader.

**Comment by rastographics** [comment]
Thanks @karenworrell . Fixed issue 2. Sent you email with new passwords I had to reset.

Regarding intended behavior...for our use case at least, if I was a group leader adding a guest, I would expect that guest to be assigned to my group.

It seems guests are not intended to be part of a sub-group though...only actual members of an Org can be added to the OrgMemMemTags table.

So at this point I can think of 2 options...
1. have a policy that only the Class Leader can add guests (not ideal), or 
2. allow ALL guests to be viewable for ALL group leaders.

I changed the code to allow ALL guest to be viewable for ALL leaders.
That seems most practical...any group leader can add a guest and mark present.
It can be up to each church what policies they want to make concerning who is responsible for marking attendance for guests...

**Comment by karenworrell** [comment]
@rastographics @davidcarroll 
I tested again this morning. It is looking good! I think this is good to go. My NOTES below are for information / documentation, not b/c they are problems.

Issue 1)
All leaders can see all guests. I think this is the best way to handle this. When a leader adds a guest and they are marked present, any other leader logging in after that will see the guest, but will also see that they are marked present.

Issue 2)
Anyone NOT in a Sub-Group is now displaying for the Group Leader whose Mbr Type matches the Org Leader Type. Also, the user sees all members of groups that do not have a Leader.

NOTES:
A Leader in the class that has full access (not OrgLeadersOnly) and who is NOT a Group Leader will see all Members and all Guests. I think this is how it should work. 

A Leader in the class that has full access (not OrgLeaderOnly) and who IS a Group Leader will see only their group and all guests. I think this is how it should work.

A Leader whose Mbr Type matches the Org Leader Type but who is NOT a Group Leader will see all Members and Guests. I think this is how it should work.

**Comment by davidcarroll** [comment]
I'll try to get this merged in before the end of the week. Thank you @rastographics and @karenworrell . Good job to both of you!

**Comment by rastographics** [comment]
Obviously I did not check in any of my modified files from the CmsData/Generated folder. I'm assuming you just re-generate that with the Dbml tool.

**Comment by davidcarroll** [comment]
Yes, that is a good approach. It is just one column in the
OrganizationMembers table right?

**Comment by rastographics** [comment]
2 columns: 
[OrgMemMemTags: isLeader [bit]](https://github.com/bvcms/bvcms/pull/110/files#diff-1ce8db782e3733b714614ab8d0875577R6)
[Organizations: AttendanceBySubgroups [bit]](https://github.com/bvcms/bvcms/pull/110/files#diff-ba7f5dcc57700597c6526bfc3613839dR81) (to turn the feature on or off per Org)

Also a 3rd sql script modified that affects the generated classes is the dbo.RollList function of course

**Comment by hkouns** [comment]
Note that I have not had a chance to login and try anything so this might be obvious if I did ... If so I apologize. 
I noticed that the feature description seems to be "Filter Attendance Roster By Subgroup".  I wonder if we should have the word "APP" in that description so that there is no confusion with the Roster Report ... Or with grouping rollsheet by subgroup prefix.  
I am not hung up on it either way... Just thought I would pose the question.

**Comment by davidcarroll** [comment]
@rastographics Your two pull requests have been code reviewed and refactored some. These are now incorporated into master. But not published to production yet. Karen will be testing tomorrow. The database changes have already been published to all church databases so those are ready to publish the code sometime tomorrow assuming things go well with a big project I have been working on for OnePageGiving for Redeemer.

**Comment by davidcarroll** [comment]
This is published to production.

**Pull request merged**
