### PR TITLE
Manage Organization Member changes

### PR DESCRIPTION
**Pull request by nehresma**
Here are several new features Heath and I have been working on.

- Support for search more than one sub group (separated by semicolon).
- Support for making sub groups a dropdown with help text.
- Support for making grades a dropdown consisting of the unique set of grades in the division and source organization.  Including help text.
- Support for an "Age" search predicate.  It supports ranges (<, <=, >, >=, N-M, or simple integers for equality).  Including help text.
- Support for a Target Division dropdown selector.
- Support for optionally changing the member's type at the same time as moving the member.
- A few small layout changes.

Feedback is appreciated.  I will be out of town for a few days but I will keep an eye on this.

### CODE REVIEW

**Comment by davidcarroll** [comment]
Thank you @nehresma and @hkouns! @karenworrell  and I will put together a plan for how and when we want to roll this out. We will need documentation in place and a blog post ready before we go to production. We will let you know.

**Comment by hkouns** [comment]
@davidcarroll , @karenworrell,  
For your information, we will promote our kids (for Sunday classes) prior to Sunday, June 5th.   In an ideal world, it would be available prior to those promotions being made later next week.   The next opportunity will be VBS which will Start on June 26th  and we will likely move volunteers and kids into crews on the 24th or 25th.  Thanks for evaluating the changes.

**Comment by karenworrell** [comment]
@hkouns @nehresma @davidcarroll 
I am testing this now and it is looking good. I don't think next week is out of the question. I'm going to try to finish testing today. Thank you both for working on this!

**Comment by davidcarroll** [comment]
I have reviewed the code and it all looks clean. Once @karenworrell is done documenting, I will merge to master and publish to production.

**Comment by nehresma** [comment]
Good to hear David.  @hkouns mentioned that Karen had a few changes yet.  I 
am out of town until the weekend but I will look into them as soon as I can.

**Comment by karenworrell** [comment]
@nehresma @hkouns @davidcarroll 
None of the things I mentioned need to be done now. They can be future enhancements. I'm documenting now. I'll need to record a couple of videos and revise 2 different docs (one for the page itself and one for using it for Promotion) so it will be a day or so before I finish. Then we'll get it out there to everyone! Thanks again for your work on this guys!

**Comment by davidcarroll** [comment]
We will postpone any other changes until this is in master and in production.

**Pull request closed without merging**
