### PR TITLE
Sql date value array

### PR DESCRIPTION
**Pull request by hkouns**

### CODE REVIEW

**Comment by davidcarroll** [comment]
Heath, It looks like you have done it again with the multiple commits in a single pull request. Somehow, we need to get only the single SqlDateValueArray file in the commit. I can just pull the code over but you will no longer get credit for it if I do that.

**Comment by hkouns** [comment]
I guess I am not understanding the intent of a single commit. I thought the issue the last time was due to making a PR on code that wasn't fully up to date with the master.

If I make several commits to the feature branch before making the PR then it will have multiple commits by default.  Are you only talking about the extra commits to update to the latest at BVCMS/Master?

Of the four commits in this PR... 

- The first was updating GSBC/master before I started the work on the feature.  
- The second is the feature itself.  
- The last two were to update the branch with the latest code so that  I could test and make sure that nothing broke.   (This could have been reduced to a single commit if I had updated the branch from BVCMS/master directly)

In the end only a single file was modified.  Are you seeing something different from your side?  How would you recommend I modify the workflow?

Thanks for you help understanding...

**Comment by davidcarroll** [comment]
Maybe this is why I prefer rebase when making pull requests. That is how Steven does it, and it comes across without all the merge commits done on your side. The rebase would be to get your master completely in sync with our master, and then replay your changes in your new branch on to that your master which is in sync with our master. Then the pull request would only contain the changed files, not all the merge files. At least, I think that is what would happen. 

I am looking at your network graph again and see that you never merged your feature branch into your master, but instead, you merged your master into your feature branch which is OK, but at some point, it needs to go back to a master that is in sync with our master on your side.

I am just comparing Steven's pull requests with yours and trying to figure out how to keep them limited to just your changes.

**Comment by hkouns** [comment]
"... you never merged your feature branch into your master, ..."

This is because we ran into issues where if I merge the feature branch back to my master before the PR is accepted to BVCMS... Then I cannot work in another feature because the first feature is now "confusing" it....

In the past we decided (I thought) to keep the features in their own branch... Then just keep updating the GSBC master to keep it in sync with BVCMS master. 

I will look into rebasing... But at the moment am not familiar...I know I can't do it with the graphical interface I normally use.

**Comment by davidcarroll** [comment]
This both the power of Git and the awful complexity of Git and its terminology that drives people crazy. I am no expert on Git that is for sure. But I am learning. 

Git Extensions http://gitextensions.github.io/ is a very nice Visual Studio addin that is very complete and does a good job (read not confusing) with rebase too.

**Comment by hkouns** [comment]
@davidcarroll  I figured out how to rebase... the PR should be clean now.

Here are the commands I used in Git Shell (from Github Desktop):
> git fetch bvcms
> git rebase bvcms/master
> git push -f origin SqlDateValueArray

**Comment by davidcarroll** [comment]
Perfect, Thank you!

**Comment by hkouns** [comment]
@davidcarroll You may have seen the trello card comment... When I publish this code to the Test site (.work) it says that "datetime" module is not available when the python script is ran.... Do you think this is something with the setup of the test site? of is it something I need to do differently?

**Comment by davidcarroll** [comment]
I'll respond in Trello

**Pull request merged**
