### PR TITLE
Support custom shells on the login page

### PR DESCRIPTION
**Pull request by drmohundro**
This pull request implements the feature so that the login page (and related views) can be displayed with a custom shell.

If the user sets an admin setting named `UX-LoginPageShell` whose value is the name of HTML special content for a shell, then that shell will be used on the login page.

### CODE REVIEW

**Comment by davidcarroll** [comment]
@drmohundro  Your pull-request been merged to master and published to test and as soon as Karen finishes testing a OnePageGiving project I have been working on as an emergency project for Redeemer, this pull-request will go to production.

**Comment by drmohundro** [comment]
No worries - I've been trying to watch the releases tab periodically to see when tags are published. I appreciate the help :)

**Comment by davidcarroll** [comment]
This is published. I notified Kayan but I assume you have told them how to use the new shell. Karen will document that for the help eventually.

**Comment by drmohundro** [comment]
Thanks @davidcarroll!

**Pull request merged**
