### PR TITLE
Latest Redeemer retainer requests

### PR DESCRIPTION
**Pull request by drmohundro**
This PR includes the following:

* Resources can now be tied to multiple organizations and/or organization types
* SGF can now have a customizable subtitle
* Custom auto promote roles
* Some basic email customizations

FYI, the below SQL will need to be run to migrate from the old Resource columns to the new Resource columns. I can handle this once it is deployed, though.

```sql
/*
migrate from single column to join table for resources
*/

;WITH ResourcesWithOrgs AS (
	SELECT *
	FROM dbo.resource
	WHERE OrganizationId IS NOT NULL
)
INSERT INTO dbo.ResourceOrganization
SELECT ResourceId, OrganizationId
FROM ResourcesWithOrgs

;WITH ResourcesWithOrgTypes AS (
	SELECT *
	FROM dbo.resource
	WHERE OrganizationTypeId IS NOT NULL
)
INSERT INTO dbo.ResourceOrganizationType
SELECT ResourceId, OrganizationTypeId
FROM ResourcesWithOrgTypes
```

### CODE REVIEW

**Comment by davidcarroll** [comment]
Looks like some fundamental things are getting changed, not just Redeemer specific. Email Controller, AddRoles, AutoPromotion, etc. What about testing to make sure there are no breaking changes?

**Comment by drmohundro** [comment]
Sorry, should have clarified but Redeemer has tested/verified this in staging.

**Comment by davidcarroll** [comment]
I have this published to our .work site so we can test email and roles. Once Karen is done with that, probably some time tomorrow, I'll push to production assuming all is well. Thanks Mo.

**Comment by davidcarroll** [comment]
This was published to production last night

**Pull request merged**
