### PR TITLE
Redeemer-requested changes

### PR DESCRIPTION
**Pull request by drmohundro**
Hi David - this PR includes the latest requested changes from Redeemer (and has been tested on staging). See below for a brief summary of the changes:

- Involvement tab (current, previous and pending)
  - Added a new admin setting to allow for hiding the organization type filters
  - Allow the previous admin setting we added also define the order of organizations displayed (e.g. if Community Group, Mailing List, Other then display in that order versus in alphabetical order)
    - side note - this did require us to `.ToList` the return early so that we can do that sorting in memory - we *only* do this early `ToList` if the admin setting is checked, though
- Custom skin for congregation login pages (i.e. campus-specific skins for the login page)
- Follow up items from our last PR to allow for further customization of meeting-pages via XML special content (see #163)
- Allow for Resources to be locked down by status flag
- Added a few minor bug fixes
  - the org search page wasn't returning results correctly if someone searched for group type of men (because it was a contains check)
  - supported deep linking of resource sub-tabs (on the profile page)

I *think* that is it, but please ping me if you have any additional questions. Thanks so much!

### CODE REVIEW

**Comment by davidcarroll** [comment]
@drmohundro when you say further customization of Meeting Pages what is that? You referred to the new XML specification file, but what does that have to do with a Meeting Page? Is that where they take attendance?

**Comment by davidcarroll** [comment]
@drmohundro Can you or Redeemer produce a brief video of all the things this changes? We just need an overview in the user interface of what all this code touches and changes so Karen can test and eventually document.

**Comment by drmohundro** [comment]
Sorry, should have clarified further. The settings from RoleChecker, like `<setting name="LimitToolbar" value="true" />`, will now also apply to the meetings pages. So, under an organization, where you can manage meetings/attendance. No new settings were added, but they also apply to Meetings just as they do for the Organizations page.

From our docs on #163, it should be these settings:

```xml
            <setting name="Meeting-HyperlinkNames" value="false" />
            <setting name="Meeting-ShowAddGuest" value="true" />
            <setting name="Meeting-AllowEditDescription" value="false" />
            <setting name="Meeting-ShowExtraValuesBox" value="false" />
            <setting name="Meeting-ShowWandTargetBox" value="false" />
            <setting name="Meeting-ShowBlueToolbar" value="false" />
            <setting name="Meeting-ShowBlueToolbarIpadAttendance" value="false" />
            <setting name="Meeting-ShowBlueToolbarRollsheet" value="false" />
            <setting name="Meeting-EnableEditByDefault" value="true" />
            <setting name="Meeting-ShowEnableBox" value="false" />
            <setting name="Meeting-ShowShowBox" value="false" />
            <setting name="Meeting-ShowAttendType" value="false" />
            <setting name="Meeting-ShowOtherAttend" value="false" />
            <setting name="Meeting-ShowCurrentMemberType" value="false" />
```

These settings were added, but the implementation to support them wasn't completed at that time as we were out of hours at that point.

**Comment by davidcarroll** [comment]
Got it, that helps. 
I still think we need a very rough cut video just visiting every page that is affected by this and just pointing to the things that affected with a brief description. I am sure you had a demo from redeemer when they asked for these changes, and you had to give one when you finished them to show that you did all the work to their sanctification. Since we were absent from either of those, we just need to get in the loop from a UI perspective (big picture), not just a code review.

**Comment by drmohundro** [comment]
We didn't have any video, but I did put some screenshots together. The below images reflect the only pages affected by the meeting / role checker enhancements.

Before:

meeting - before

After:

meeting - after

**Comment by davidcarroll** [comment]
So that is the only user interface change made across 23 files?

**Comment by drmohundro** [comment]
Sorry I misunderstood - within the context, I read "this change" and the prior comment was about meetings. Give me a bit and I'll get some more screenshots for the other changes.

**Comment by drmohundro** [comment]
See below.

Custom Skin - Before:

custom skin logon - before

Custom Skin - After:

custom skin logon - after

Involvement tab - Before:

involvement tab - before

Involvement tab - After:

involvement tab - after

Edit Resource - Before:

edit resource - before

Edit Resource - After:

edit resource - after

Add Resource - Before:

add resource - before

Add Resource - After:

add resource - after

**Comment by davidcarroll** [comment]
This is published to production

**Comment by davidcarroll** [comment]
Mo, I reset master back to merging your pull request, and published to production. So this is now in the same state it was in prior to the merge. I am going to let you test and fix these bugs. Basically, you need to make sure this works for other non-redeemer churches and not just for redeemer.  We will need to point your iis site to trialdb or some other database than redeemer to test with.

**Pull request merged**
